### ISSUE TITLE
请教怎样修改

### ISSUE THREAD

**Issue by hidfgidh** [nv-dvl/nerfmatch#3]
您好，我在执行训练的7场景的最后一步时，输入# NeRFMatch
torchrun --nproc_per_node=4  model_train/train_nerfmatch_c2f.py \
    --config configs/nerfmatch/nerfmatch_7scenes_sfm_c2f.yaml \
    --backbone 'convformer384' --temp_type 'mul' --batch_size 2 \
    --max_epochs 50 --clr 0.0004 --cbs 16 --pair_topk 30  --aug_self_pairs 10 \
    --scene_dir  'outputs/scene_dirs/7scenes/sfm/inter_layer3/#scene/mip/last_15ep/ds8lin' \
    --resume_version 'mip_inter3_last' --update_conf \
    --prefix 'eccv/repr' --scenes 'heads'

但是会在服务器上报错
请问该怎样修改呢？谢谢

**Comment by hidfgidh** [comment]
[Uploading 报错信息.txt…]()

**Comment by hidfgidh** [comment]
[Uploading 报错信息.txt…]()

**Comment by GrumpyZhou** [comment]
你可以把你的报错po一下吗

**Comment by hidfgidh** [comment]
非常抱歉耽误您的时间，虽然昨晚我上传了错误信息，但是不知道什么原因不可见了
以下是输入默认训练最后一步命令(显卡数量我改为了4,并且在训练前已经确认服务器上无其他深度学习任务)后的输出
我在百度上搜索这个错误，说是要改动pytorch-lighting和torch的版本，但是在此之前已经对其版本做了对应，确认两者版本匹配
`@server-SYS-7048GR-TR:~/nerfmatch$ torchrun --nproc_per_node=4  model_train/train_nerfmatch_c2f.py \
>     --config configs/nerfmatch/nerfmatch_7scenes_sfm_c2f.yaml \
>     --backbone 'convformer384' --temp_type 'mul' --batch_size 2 \
>     --max_epochs 50 --clr 0.0004 --cbs 16 --pair_topk 30  --aug_self_pairs 10 \
>     --scene_dir  'outputs/scene_dirs/7scenes/sfm/inter_layer3/#scene/mip/last_15ep/ds8lin' \
>     --resume_version 'mip_inter3_last' --update_conf \
>     --prefix 'eccv/repr' --scenes 'heads'
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
[rank: 0] Global seed set to 12343
True batch: 8 lr: 0.0002 
[2024-10-15 08:51:09|trainer|INFO]: Namespace(data=Namespace(dataset='NeRFMatchPair', data_dir='data/7scenes', scenes=['heads'], scene_anno_path='data/annotations/7scenes_jsons/sfm/transforms_#scene_#split.json', scene_dir='outputs/scene_dirs/7scenes/sfm/inter_layer3/#scene/mip/last_15ep/ds8lin', train_pair_txt='data/pairs/7scenes/#scene/pairs-db-covis30.txt', test_pair_txt='data/pairs/7scenes/#scene/pairs-query-densevlad10.txt', pair_topk=30, img_wh=[480, 480], img_dim=3, use_msk=False, model_ds=8, balanced_pair=True, imagenet_norm=True, epoch_sample_num=10000, aug_self_pairs=10), optim=Namespace(optimizer='adam', adapt_lr=True, clr=0.0004, cbs=16, weight_decay=0.0, lr_scheduler='cosine', coarse_only_epochs=0, max_epochs=50, lr=0.0002), model=Namespace(backbone='convformer384', pretrained=True, im_pe=True, im_sa_type='share', im_sa=3, temp_type='mul', pt_sa=3, pt_dim=256, pt_sa_type='full', pt_pe=True, pt_pe_type='fourier', post_pt_pe=True, cfeat_dim=256, ffeat_dim=128, cformer_type='crs', coarse_layers=1, pt_ftype='nerf', fine_sa=1, fsa_type='full', win_sz=5, cat_c_feat=True, fine_loss='match', coarse_percent=0.3, coarse_dthres=10, coarse_ckpt=None, c2f_ckpt=None), exp=Namespace(seed=12343, odir=PosixPath('outputs/nerfmatch/c2f/7scenes/sfm'), prefix='eccv/repr', resume_version='mip_inter3_last', num_workers=4, max_epochs=50, check_epochs=1, batch_size=2, debug=False, name='eccv/repr/NeRFMatchPair_heads_wh480-480ds8lin_top30ep10000_bala_imn_slfaug10/convformer384_pre_imp_ptp_ptfull3_pepos_imsa_share_cfcrs1d256_multmp_fsafull1d128w5_catc_match0.3d10/g4clr0.0004cbs16adamcosine_ep50'), gpus=-1, prefix='eccv/repr', debug=False, config='configs/nerfmatch/nerfmatch_7scenes_sfm_c2f.yaml', coarse_ckpt=None, c2f_ckpt=None, backbone='convformer384', cformer_type='crs', coarse_layers=1, pt_sa=3, im_sa=3, pt_dim=256, cfeat_dim=256, pt_pe=True, im_pe=True, im_sa_type='share', pt_sa_type='full', pt_ftype='nerf', pt_pe_type='fourier', temp_type='mul', fine_sa=1, fsa_type='full', update_conf=True, batch_size=2, clr=0.0004, cbs=16, adapt_lr=False, max_epochs=50, coarse_only_epochs=0, epoch_sample_num=10000, pair_topk=30, aug_self_pairs=10, train_pair_txt=None, scene_dir='outputs/scene_dirs/7scenes/sfm/inter_layer3/#scene/mip/last_15ep/ds8lin', scenes=['heads'], resume_version='mip_inter3_last', gpu_num=4)
[rank: 2] Global seed set to 12343
True batch: 8 lr: 0.0002 
[2024-10-15 08:51:09|trainer|INFO]: Namespace(data=Namespace(dataset='NeRFMatchPair', data_dir='data/7scenes', scenes=['heads'], scene_anno_path='data/annotations/7scenes_jsons/sfm/transforms_#scene_#split.json', scene_dir='outputs/scene_dirs/7scenes/sfm/inter_layer3/#scene/mip/last_15ep/ds8lin', train_pair_txt='data/pairs/7scenes/#scene/pairs-db-covis30.txt', test_pair_txt='data/pairs/7scenes/#scene/pairs-query-densevlad10.txt', pair_topk=30, img_wh=[480, 480], img_dim=3, use_msk=False, model_ds=8, balanced_pair=True, imagenet_norm=True, epoch_sample_num=10000, aug_self_pairs=10), optim=Namespace(optimizer='adam', adapt_lr=True, clr=0.0004, cbs=16, weight_decay=0.0, lr_scheduler='cosine', coarse_only_epochs=0, max_epochs=50, lr=0.0002), model=Namespace(backbone='convformer384', pretrained=True, im_pe=True, im_sa_type='share', im_sa=3, temp_type='mul', pt_sa=3, pt_dim=256, pt_sa_type='full', pt_pe=True, pt_pe_type='fourier', post_pt_pe=True, cfeat_dim=256, ffeat_dim=128, cformer_type='crs', coarse_layers=1, pt_ftype='nerf', fine_sa=1, fsa_type='full', win_sz=5, cat_c_feat=True, fine_loss='match', coarse_percent=0.3, coarse_dthres=10, coarse_ckpt=None, c2f_ckpt=None), exp=Namespace(seed=12343, odir=PosixPath('outputs/nerfmatch/c2f/7scenes/sfm'), prefix='eccv/repr', resume_version='mip_inter3_last', num_workers=4, max_epochs=50, check_epochs=1, batch_size=2, debug=False, name='eccv/repr/NeRFMatchPair_heads_wh480-480ds8lin_top30ep10000_bala_imn_slfaug10/convformer384_pre_imp_ptp_ptfull3_pepos_imsa_share_cfcrs1d256_multmp_fsafull1d128w5_catc_match0.3d10/g4clr0.0004cbs16adamcosine_ep50'), gpus=-1, prefix='eccv/repr', debug=False, config='configs/nerfmatch/nerfmatch_7scenes_sfm_c2f.yaml', coarse_ckpt=None, c2f_ckpt=None, backbone='convformer384', cformer_type='crs', coarse_layers=1, pt_sa=3, im_sa=3, pt_dim=256, cfeat_dim=256, pt_pe=True, im_pe=True, im_sa_type='share', pt_sa_type='full', pt_ftype='nerf', pt_pe_type='fourier', temp_type='mul', fine_sa=1, fsa_type='full', update_conf=True, batch_size=2, clr=0.0004, cbs=16, adapt_lr=False, max_epochs=50, coarse_only_epochs=0, epoch_sample_num=10000, pair_topk=30, aug_self_pairs=10, train_pair_txt=None, scene_dir='outputs/scene_dirs/7scenes/sfm/inter_layer3/#scene/mip/last_15ep/ds8lin', scenes=['heads'], resume_version='mip_inter3_last', gpu_num=4)
Traceback (most recent call last):
  File "/data/users/nerfmatch/model_train/train_nerfmatch_c2f.py", line 110, in <module>
    main()
  File "/data/usersnerfmatch/model_train/train_nerfmatch_c2f.py", line 106, in main
    train(config)
  File "/data/users/nerfmatch/model_train/nerfmatch/nerfmatch_c2f_trainer.py", line 846, in train
    None if gpu_num <= 1 else pl.plugins.DDPPlugin(find_unused_parameters=True)
  File "/data/users/anaconda3/envs/neumatch/lib/python3.9/site-packages/pytorch_lightning/_graveyard/training_type.py", line 45, in _ttp_constructor
    raise NotImplementedError(
NotImplementedError: The `pl.plugins.DDPPlugin` class was deprecated in v1.6 and is no longer supported as of v1.8. Use `pl.strategies.DDPStrategy` instead.
[rank: 1] Global seed set to 12343
True batch: 8 lr: 0.0002 
[2024-10-15 08:51:10|trainer|INFO]: Namespace(data=Namespace(dataset='NeRFMatchPair', data_dir='data/7scenes', scenes=['heads'], scene_anno_path='data/annotations/7scenes_jsons/sfm/transforms_#scene_#split.json', scene_dir='outputs/scene_dirs/7scenes/sfm/inter_layer3/#scene/mip/last_15ep/ds8lin', train_pair_txt='data/pairs/7scenes/#scene/pairs-db-covis30.txt', test_pair_txt='data/pairs/7scenes/#scene/pairs-query-densevlad10.txt', pair_topk=30, img_wh=[480, 480], img_dim=3, use_msk=False, model_ds=8, balanced_pair=True, imagenet_norm=True, epoch_sample_num=10000, aug_self_pairs=10), optim=Namespace(optimizer='adam', adapt_lr=True, clr=0.0004, cbs=16, weight_decay=0.0, lr_scheduler='cosine', coarse_only_epochs=0, max_epochs=50, lr=0.0002), model=Namespace(backbone='convformer384', pretrained=True, im_pe=True, im_sa_type='share', im_sa=3, temp_type='mul', pt_sa=3, pt_dim=256, pt_sa_type='full', pt_pe=True, pt_pe_type='fourier', post_pt_pe=True, cfeat_dim=256, ffeat_dim=128, cformer_type='crs', coarse_layers=1, pt_ftype='nerf', fine_sa=1, fsa_type='full', win_sz=5, cat_c_feat=True, fine_loss='match', coarse_percent=0.3, coarse_dthres=10, coarse_ckpt=None, c2f_ckpt=None), exp=Namespace(seed=12343, odir=PosixPath('outputs/nerfmatch/c2f/7scenes/sfm'), prefix='eccv/repr', resume_version='mip_inter3_last', num_workers=4, max_epochs=50, check_epochs=1, batch_size=2, debug=False, name='eccv/repr/NeRFMatchPair_heads_wh480-480ds8lin_top30ep10000_bala_imn_slfaug10/convformer384_pre_imp_ptp_ptfull3_pepos_imsa_share_cfcrs1d256_multmp_fsafull1d128w5_catc_match0.3d10/g4clr0.0004cbs16adamcosine_ep50'), gpus=-1, prefix='eccv/repr', debug=False, config='configs/nerfmatch/nerfmatch_7scenes_sfm_c2f.yaml', coarse_ckpt=None, c2f_ckpt=None, backbone='convformer384', cformer_type='crs', coarse_layers=1, pt_sa=3, im_sa=3, pt_dim=256, cfeat_dim=256, pt_pe=True, im_pe=True, im_sa_type='share', pt_sa_type='full', pt_ftype='nerf', pt_pe_type='fourier', temp_type='mul', fine_sa=1, fsa_type='full', update_conf=True, batch_size=2, clr=0.0004, cbs=16, adapt_lr=False, max_epochs=50, coarse_only_epochs=0, epoch_sample_num=10000, pair_topk=30, aug_self_pairs=10, train_pair_txt=None, scene_dir='outputs/scene_dirs/7scenes/sfm/inter_layer3/#scene/mip/last_15ep/ds8lin', scenes=['heads'], resume_version='mip_inter3_last', gpu_num=4)
Traceback (most recent call last):
  File "/data/users/nerfmatch/model_train/train_nerfmatch_c2f.py", line 110, in <module>
    main()
  File "/data/users/nerfmatch/model_train/train_nerfmatch_c2f.py", line 106, in main
    train(config)
  File "/data/users/nerfmatch/model_train/nerfmatch/nerfmatch_c2f_trainer.py", line 846, in train
    None if gpu_num <= 1 else pl.plugins.DDPPlugin(find_unused_parameters=True)
  File "/data/users/anaconda3/envs/neumatch/lib/python3.9/site-packages/pytorch_lightning/_graveyard/training_type.py", line 45, in _ttp_constructor
    raise NotImplementedError(
NotImplementedError: The `pl.plugins.DDPPlugin` class was deprecated in v1.6 and is no longer supported as of v1.8. Use `pl.strategies.DDPStrategy` instead.
[rank: 3] Global seed set to 12343
True batch: 8 lr: 0.0002 
[2024-10-15 08:51:10|trainer|INFO]: Namespace(data=Namespace(dataset='NeRFMatchPair', data_dir='data/7scenes', scenes=['heads'], scene_anno_path='data/annotations/7scenes_jsons/sfm/transforms_#scene_#split.json', scene_dir='outputs/scene_dirs/7scenes/sfm/inter_layer3/#scene/mip/last_15ep/ds8lin', train_pair_txt='data/pairs/7scenes/#scene/pairs-db-covis30.txt', test_pair_txt='data/pairs/7scenes/#scene/pairs-query-densevlad10.txt', pair_topk=30, img_wh=[480, 480], img_dim=3, use_msk=False, model_ds=8, balanced_pair=True, imagenet_norm=True, epoch_sample_num=10000, aug_self_pairs=10), optim=Namespace(optimizer='adam', adapt_lr=True, clr=0.0004, cbs=16, weight_decay=0.0, lr_scheduler='cosine', coarse_only_epochs=0, max_epochs=50, lr=0.0002), model=Namespace(backbone='convformer384', pretrained=True, im_pe=True, im_sa_type='share', im_sa=3, temp_type='mul', pt_sa=3, pt_dim=256, pt_sa_type='full', pt_pe=True, pt_pe_type='fourier', post_pt_pe=True, cfeat_dim=256, ffeat_dim=128, cformer_type='crs', coarse_layers=1, pt_ftype='nerf', fine_sa=1, fsa_type='full', win_sz=5, cat_c_feat=True, fine_loss='match', coarse_percent=0.3, coarse_dthres=10, coarse_ckpt=None, c2f_ckpt=None), exp=Namespace(seed=12343, odir=PosixPath('outputs/nerfmatch/c2f/7scenes/sfm'), prefix='eccv/repr', resume_version='mip_inter3_last', num_workers=4, max_epochs=50, check_epochs=1, batch_size=2, debug=False, name='eccv/repr/NeRFMatchPair_heads_wh480-480ds8lin_top30ep10000_bala_imn_slfaug10/convformer384_pre_imp_ptp_ptfull3_pepos_imsa_share_cfcrs1d256_multmp_fsafull1d128w5_catc_match0.3d10/g4clr0.0004cbs16adamcosine_ep50'), gpus=-1, prefix='eccv/repr', debug=False, config='configs/nerfmatch/nerfmatch_7scenes_sfm_c2f.yaml', coarse_ckpt=None, c2f_ckpt=None, backbone='convformer384', cformer_type='crs', coarse_layers=1, pt_sa=3, im_sa=3, pt_dim=256, cfeat_dim=256, pt_pe=True, im_pe=True, im_sa_type='share', pt_sa_type='full', pt_ftype='nerf', pt_pe_type='fourier', temp_type='mul', fine_sa=1, fsa_type='full', update_conf=True, batch_size=2, clr=0.0004, cbs=16, adapt_lr=False, max_epochs=50, coarse_only_epochs=0, epoch_sample_num=10000, pair_topk=30, aug_self_pairs=10, train_pair_txt=None, scene_dir='outputs/scene_dirs/7scenes/sfm/inter_layer3/#scene/mip/last_15ep/ds8lin', scenes=['heads'], resume_version='mip_inter3_last', gpu_num=4)
Traceback (most recent call last):
  File "/data/users/nerfmatch/model_train/train_nerfmatch_c2f.py", line 110, in <module>
    main()
  File "/data/users/nerfmatch/model_train/train_nerfmatch_c2f.py", line 106, in main
    train(config)
  File "/data/users/nerfmatch/model_train/nerfmatch/nerfmatch_c2f_trainer.py", line 846, in train
    None if gpu_num <= 1 else pl.plugins.DDPPlugin(find_unused_parameters=True)
  File "/data/users/ligangzhang/anaconda3/envs/neumatch/lib/python3.9/site-packages/pytorch_lightning/_graveyard/training_type.py", line 45, in _ttp_constructor
    raise NotImplementedError(
NotImplementedError: The `pl.plugins.DDPPlugin` class was deprecated in v1.6 and is no longer supported as of v1.8. Use `pl.strategies.DDPStrategy` instead.
Traceback (most recent call last):
  File "/data/users/nerfmatch/model_train/train_nerfmatch_c2f.py", line 110, in <module>
    main()
  File "/data/users/nerfmatch/model_train/train_nerfmatch_c2f.py", line 106, in main
    train(config)
  File "/data/users/nerfmatch/model_train/nerfmatch/nerfmatch_c2f_trainer.py", line 846, in train
    None if gpu_num <= 1 else pl.plugins.DDPPlugin(find_unused_parameters=True)
  File "/data/users/ligangzhang/anaconda3/envs/neumatch/lib/python3.9/site-packages/pytorch_lightning/_graveyard/training_type.py", line 45, in _ttp_constructor
    raise NotImplementedError(
NotImplementedError: The `pl.plugins.DDPPlugin` class was deprecated in v1.6 and is no longer supported as of v1.8. Use `pl.strategies.DDPStrategy` instead.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 313820) of binary: /data/users/anaconda3/envs/neumatch/bin/python
Traceback (most recent call last):
  File "/data/users/anaconda3/envs/neumatch/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/data/users/anaconda3/envs/neumatch/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/data/users/anaconda3/envs/neumatch/lib/python3.9/site-packages/torch/distributed/run.py", line 761, in main
    run(args)
  File "/data/users/anaconda3/envs/neumatch/lib/python3.9/site-packages/torch/distributed/run.py", line 752, in run
    elastic_launch(
  File "/data/users/anaconda3/envs/neumatch/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/data/users/anaconda3/envs/neumatch/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
model_train/train_nerfmatch_c2f.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-10-15_08:51:12
  host      : server-SYS-7048GR-TR
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 313821)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-10-15_08:51:12
  host      : server-SYS-7048GR-TR
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 313822)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2024-10-15_08:51:12
  host      : server-SYS-7048GR-TR
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 313823)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-10-15_08:51:12
  host      : server-SYS-7048GR-TR
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 313820)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
`

**Comment by hidfgidh** [comment]
非常抱歉耽误您的时间，我昨天晚上上传了错误信息，但是今天早上发现没有成功
对于发生的错误，我在csdn上搜索的修改方法是对pytorch-lighting和torch做一个兼容，但是在安装的时候，我安装的就是二者的兼容的版本，并且在跑这条命令之前，确认服务器上无其他深度学习任务，今天早上重新输入代码训练，发现还是一样的错误，错误如下
https://drive.google.com/file/d/1IwgdC45Dmq9iH4NHgEdWHAANzV0mnWNF/view?usp=drive_link
